"""Citation-graph enrichment via the Semantic Scholar Graph API.

For each library item (budgeted, ~1 req/1.3s, stops on HTTP 429):
- citation count + S2 paper id stored in state,
- reference DOIs/arXiv ids matched against the library -> in-library citation
  edges (state.citations).

Vault output: 30_Resources/Papers/Citation_Graph.md — a ZotVault-OWNED,
auto-regenerated note. Human paper notes are never modified (M1 guarantee).
"""
from __future__ import annotations

import datetime as _dt
import json
import logging
import time
import urllib.error
import urllib.parse
import urllib.request
from pathlib import Path
from typing import Any, Dict, List, Optional

from zotvault import __version__
from zotvault.config import Config
from zotvault.state import State

log = logging.getLogger("zotvault.enrich")

_S2 = "https://api.semanticscholar.org/graph/v1/paper/"
_FIELDS = "citationCount,externalIds,references.externalIds"

AUTO_HEADER = (
    "> ⚠️ AUTO-GENERATED by ZotVault (`zotvault enrich`) — edits will be "
    "overwritten. Source of truth: Semantic Scholar + local state.\n"
)


def s2_fetch(ident: str, api_key: str = "", timeout: int = 20) -> Optional[Dict[str, Any]]:
    url = _S2 + urllib.parse.quote(ident) + "?fields=" + _FIELDS
    headers = {"User-Agent": "ZotVault/{}".format(__version__)}
    if api_key:
        headers["x-api-key"] = api_key
    req = urllib.request.Request(url, headers=headers)
    with urllib.request.urlopen(req, timeout=timeout) as resp:
        return json.loads(resp.read().decode("utf-8"))


def run(cfg: Config, state: State, limit: Optional[int] = None) -> int:
    budget = limit or cfg.enrich_budget_per_run
    rows = state.items_for_enrich(budget)
    if not rows:
        return 0
    doi_map = state.doi_map()
    arxiv_map = state.arxiv_map()
    done = 0
    now = _dt.datetime.now().isoformat(timespec="seconds")
    for row in rows:
        ident = "DOI:" + row["doi"] if row["doi"] else "arXiv:" + row["arxiv_id"]
        try:
            data = s2_fetch(ident, cfg.s2_api_key, cfg.download_timeout_sec)
        except urllib.error.HTTPError as exc:
            if exc.code == 404:
                state.upsert_item(row["item_id"], enriched_at=now)  # known-missing
                continue
            if exc.code == 429:
                log.info("Semantic Scholar rate limit hit — resuming next run")
                state.trace("enrich_rate_limited", "", "{} of {} done".format(done, len(rows)))
                break
            log.warning("S2 %s for %s", exc.code, ident)
            continue
        except Exception as exc:
            log.warning("S2 fetch failed for %s: %s", ident, exc)
            continue
        finally:
            time.sleep(1.3)
        if not data:
            continue
        cited: List[str] = []
        for ref in data.get("references") or []:
            ext = ref.get("externalIds") or {}
            ck = doi_map.get((ext.get("DOI") or "").lower()) or \
                arxiv_map.get((ext.get("ArXiv") or "").lower().split("v")[0])
            if ck and ck != row["citekey"]:
                cited.append(ck)
        state.cite_replace(row["citekey"], sorted(set(cited)))
        state.upsert_item(
            row["item_id"],
            citation_count=data.get("citationCount"),
            s2_id=data.get("paperId"),
            enriched_at=now,
        )
        done += 1
    if done:
        state.trace("enrich_run", "", "{} item(s) enriched".format(done))
        write_citation_graph_note(cfg, state)
    return done


def note_path(cfg: Config) -> Optional[Path]:
    if cfg.papers_dir is None:
        return None
    return cfg.papers_dir.parent / "Citation_Graph.md"


def render_citation_graph(state: State) -> str:
    edges = state.cite_edges()
    cites: Dict[str, List[str]] = {}
    cited_by: Dict[str, List[str]] = {}
    for e in edges:
        cites.setdefault(e["citing"], []).append(e["cited"])
        cited_by.setdefault(e["cited"], []).append(e["citing"])
    items = {r["citekey"]: r for r in state.all_items() if r["citekey"]}
    top = sorted(
        (r for r in items.values() if r["citation_count"] is not None),
        key=lambda r: -(r["citation_count"] or 0),
    )[:20]

    lines = [
        "---",
        "type: source",
        "title: Citation Graph (in-library)",
        "tags: [ZotVault, CitationGraph, Auto]",
        "updated: " + _dt.date.today().isoformat(),
        "---",
        "",
        "# Citation Graph (in-library)",
        "",
        AUTO_HEADER,
        "In-library edges: **{}** · papers with edges: **{}**".format(
            len(edges), len(set(list(cites) + list(cited_by)))),
        "",
        "## Most cited globally (Semantic Scholar citationCount)",
        "",
        "| paper | citations |",
        "|---|---|",
    ]
    for r in top:
        lines.append("| [[{}]] | {} |".format(r["citekey"], r["citation_count"]))
    lines += ["", "## Edges (A cites B, both in library)", ""]
    for citing in sorted(cites):
        lines.append("- [[{}]] → {}".format(
            citing, " · ".join("[[{}]]".format(c) for c in sorted(cites[citing]))))
    lines += ["", "## Most cited within my library", ""]
    ranked = sorted(cited_by.items(), key=lambda kv: -len(kv[1]))[:15]
    for ck, sources in ranked:
        lines.append("- [[{}]] ← {} in-library citation(s)".format(ck, len(sources)))
    lines.append("")
    return "\n".join(lines)


def write_citation_graph_note(cfg: Config, state: State) -> bool:
    path = note_path(cfg)
    if path is None:
        return False
    content = render_citation_graph(state)
    if path.exists() and path.read_text(encoding="utf-8") == content:
        return False
    if not cfg.dry_run:
        path.write_text(content, encoding="utf-8")
        state.trace("citation_graph_note", path.name, "regenerated")
    return True
