"""Related-paper suggestions via local embeddings (Ollama, free, offline).

Embedding source per paper: the Claude analysis note when present (richest
signal), else the paper note itself. Vectors live in state.embeddings.

Vault output: 30_Resources/Papers/Related_Suggestions.md — PaperFlow-owned,
auto-regenerated. Suggestions are candidates for the human/agent to link in
`## Related` sections; PaperFlow never edits paper notes itself.
"""
from __future__ import annotations

import datetime as _dt
import json
import logging
import math
import urllib.request
from array import array
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

from paperflow import analysis_queue
from paperflow.config import Config
from paperflow.state import State

log = logging.getLogger("paperflow.related")

AUTO_HEADER = (
    "> ⚠️ AUTO-GENERATED by PaperFlow (`paperflow enrich`) — edits will be "
    "overwritten. These are *candidates* for `## Related` links; PaperFlow "
    "never edits paper notes itself.\n"
)

_MAX_CHARS = 6000


def vec_to_blob(vec: List[float]) -> bytes:
    return array("f", vec).tobytes()


def blob_to_vec(blob: bytes) -> List[float]:
    a = array("f")
    a.frombytes(blob)
    return list(a)


def cosine(a: List[float], b: List[float]) -> float:
    if not a or not b or len(a) != len(b):
        return 0.0
    dot = sum(x * y for x, y in zip(a, b))
    na = math.sqrt(sum(x * x for x in a))
    nb = math.sqrt(sum(y * y for y in b))
    if na == 0 or nb == 0:
        return 0.0
    return dot / (na * nb)


def ollama_embed(text: str, cfg: Config, timeout: int = 60) -> List[float]:
    payload = json.dumps({
        "model": cfg.ollama_embed_model,
        "prompt": text[:_MAX_CHARS],
    }).encode("utf-8")
    req = urllib.request.Request(
        cfg.ollama_url + "/api/embeddings",
        data=payload,
        headers={"Content-Type": "application/json"},
    )
    with urllib.request.urlopen(req, timeout=timeout) as resp:
        data = json.loads(resp.read().decode("utf-8"))
    emb = data.get("embedding") or []
    if not emb:
        raise ValueError("empty embedding from Ollama")
    return emb


def _source_file(cfg: Config, entry: analysis_queue.QueueEntry) -> Optional[Path]:
    if entry.analysis_files:
        return entry.folder / entry.analysis_files[0]
    note = entry.folder / (entry.citekey + ".md")
    return note if note.exists() else None


def refresh(cfg: Config, state: State, budget: Optional[int] = None) -> int:
    """Embed new/updated papers. Returns count refreshed; 0 if Ollama is down."""
    if cfg.papers_dir is None:
        return 0
    limit = budget or cfg.embed_budget_per_run
    done = 0
    for entry in analysis_queue.scan(cfg.papers_dir):
        if done >= limit:
            break
        src = _source_file(cfg, entry)
        if src is None:
            continue
        mtime = src.stat().st_mtime
        row = state.emb_get(entry.citekey)
        if row is not None and row["model"] == cfg.ollama_embed_model and \
                (row["src_mtime"] or 0) >= mtime:
            continue
        try:
            text = src.read_text(encoding="utf-8", errors="replace")
            vec = ollama_embed(text, cfg)
        except Exception as exc:
            log.info("embeddings unavailable (%s) — skipping related-paper refresh", exc)
            state.trace("embed_unavailable", entry.citekey, str(exc)[:200])
            return done
        state.emb_set(entry.citekey, cfg.ollama_embed_model, len(vec),
                      vec_to_blob(vec), mtime)
        done += 1
    if done:
        state.trace("embeddings_refreshed", "", "{} paper(s)".format(done))
    return done


def load_vectors(state: State, model: str) -> Dict[str, List[float]]:
    return {r["citekey"]: blob_to_vec(r["vec"]) for r in state.emb_all(model)}


def top_similar(citekey: str, vectors: Dict[str, List[float]], k: int = 5,
                threshold: float = 0.0) -> List[Tuple[str, float]]:
    if citekey not in vectors:
        return []
    base = vectors[citekey]
    scored = [(other, cosine(base, v)) for other, v in vectors.items() if other != citekey]
    scored.sort(key=lambda t: -t[1])
    return [(c, round(s, 4)) for c, s in scored[:k] if s >= threshold]


def related_for(citekey: str, cfg: Config, state: State) -> Any:
    vectors = load_vectors(state, cfg.ollama_embed_model)
    if citekey not in vectors:
        return {"error": "no embedding for {} — run `paperflow enrich` first".format(citekey)}
    return [{"citekey": c, "score": s}
            for c, s in top_similar(citekey, vectors, k=8, threshold=0.0)]


def note_path(cfg: Config) -> Optional[Path]:
    if cfg.papers_dir is None:
        return None
    return cfg.papers_dir.parent / "Related_Suggestions.md"


def render_note(cfg: Config, state: State) -> str:
    vectors = load_vectors(state, cfg.ollama_embed_model)
    lines = [
        "---",
        "type: source",
        "title: Related Paper Suggestions (embeddings)",
        "tags: [PaperFlow, Related, Auto]",
        "updated: " + _dt.date.today().isoformat(),
        "---",
        "",
        "# Related Paper Suggestions",
        "",
        AUTO_HEADER,
        "Model: `{}` · papers embedded: **{}** · threshold ≥ {}".format(
            cfg.ollama_embed_model, len(vectors), cfg.related_threshold),
        "",
    ]
    any_pairs = False
    for citekey in sorted(vectors):
        sims = top_similar(citekey, vectors, k=5, threshold=cfg.related_threshold)
        if not sims:
            continue
        any_pairs = True
        lines.append("- [[{}]] → {}".format(
            citekey, " · ".join("[[{}]] ({:.2f})".format(c, s) for c, s in sims)))
    if not any_pairs:
        lines.append("_no pairs above threshold yet_")
    lines.append("")
    return "\n".join(lines)


def write_note(cfg: Config, state: State) -> bool:
    path = note_path(cfg)
    if path is None or not load_vectors(state, cfg.ollama_embed_model):
        return False
    content = render_note(cfg, state)
    if path.exists() and path.read_text(encoding="utf-8") == content:
        return False
    if not cfg.dry_run:
        path.write_text(content, encoding="utf-8")
        state.trace("related_note", path.name, "regenerated")
    return True
