"""Synthesis suggestions: cluster analyzed-but-unsynthesized papers.

Uses the local embeddings (related.py) with simple greedy leader clustering —
no dependencies, deterministic, good enough to say "these 6 papers probably
belong in one synthesis note". Writing the actual synthesis stays a human/
Claude job (per the vault's synthesis contract: analysis notes only).

Vault output (opt): 30_Resources/Papers/syntheses/_Synthesis_Suggestions.md
(underscore prefix so it sorts away from real syntheses; PaperFlow-owned).
"""
from __future__ import annotations

import datetime as _dt
import logging
import re
from collections import Counter
from pathlib import Path
from typing import Any, Dict, List, Set

from paperflow import related
from paperflow.config import Config
from paperflow.state import State

log = logging.getLogger("paperflow.synthesis")

_WIKILINK_RE = re.compile(r"\[\[([^\]|#]+)")

_STOP = {
    "the", "a", "an", "of", "in", "on", "for", "and", "or", "with", "via", "from",
    "to", "by", "at", "into", "using", "based", "study", "studies", "effect",
    "effects", "properties", "first", "principles", "first-principles", "ab",
    "initio", "two", "dimensional", "two-dimensional", "2d", "monolayer",
    "monolayers", "layered", "materials", "material",
}

AUTO_HEADER = (
    "> ⚠️ AUTO-GENERATED by PaperFlow — cluster *suggestions* only. Write real "
    "syntheses via the vault contract (analysis notes only, no PDF re-reads); "
    "delete entries here by simply covering the papers in a synthesis.\n"
)


def covered_citekeys(cfg: Config) -> Set[str]:
    """Citekeys already referenced by an existing synthesis note."""
    out: Set[str] = set()
    if cfg.papers_dir is None:
        return out
    syn_dir = cfg.papers_dir.parent / "syntheses"
    if not syn_dir.exists():
        return out
    for f in syn_dir.glob("*.md"):
        if f.name.startswith("_"):
            continue
        try:
            text = f.read_text(encoding="utf-8", errors="replace")
        except OSError:
            continue
        for m in _WIKILINK_RE.finditer(text):
            out.add(m.group(1).strip())
    return out


def leader_cluster(vectors: Dict[str, List[float]], keys: List[str],
                   threshold: float) -> List[List[str]]:
    """Greedy leader clustering: deterministic, O(n·k)."""
    leaders: List[str] = []
    clusters: Dict[str, List[str]] = {}
    for key in sorted(keys):
        best, best_sim = None, threshold
        for lead in leaders:
            sim = related.cosine(vectors[key], vectors[lead])
            if sim >= best_sim:
                best, best_sim = lead, sim
        if best is None:
            leaders.append(key)
            clusters[key] = [key]
        else:
            clusters[best].append(key)
    return list(clusters.values())


def label_for(citekeys: List[str], titles: Dict[str, str]) -> str:
    words: Counter = Counter()
    for ck in citekeys:
        for w in re.findall(r"[A-Za-z][A-Za-z0-9\-]{2,}", titles.get(ck, "")):
            lw = w.lower()
            if lw not in _STOP:
                words[lw] += 1
    top = [w for w, _ in words.most_common(4)]
    return " / ".join(top) if top else "unlabeled cluster"


def suggest(cfg: Config, state: State, write_note: bool = False) -> List[Dict[str, Any]]:
    vectors = related.load_vectors(state, cfg.ollama_embed_model)
    if not vectors:
        return []
    covered = covered_citekeys(cfg)
    titles = {r["citekey"]: (r["title"] or "") for r in state.all_items() if r["citekey"]}
    analyzed = {r["citekey"] for r in state.all_items()
                if r["citekey"] and r["analysis_done"]}
    candidates = [ck for ck in vectors if ck in analyzed and ck not in covered]
    clusters = [c for c in leader_cluster(vectors, candidates, cfg.synthesis_threshold)
                if len(c) >= cfg.synthesis_min_cluster]
    out = [{"label": label_for(c, titles), "citekeys": sorted(c)} for c in clusters]
    out.sort(key=lambda c: -len(c["citekeys"]))
    if write_note and out:
        _write_note(cfg, state, out)
    return out


def _write_note(cfg: Config, state: State, clusters: List[Dict[str, Any]]) -> bool:
    if cfg.papers_dir is None:
        return False
    syn_dir = cfg.papers_dir.parent / "syntheses"
    if not syn_dir.exists():
        return False
    path = syn_dir / "_Synthesis_Suggestions.md"
    lines = [
        "---",
        "type: source",
        "title: Synthesis Suggestions (auto)",
        "tags: [PaperFlow, Synthesis, Auto]",
        "updated: " + _dt.date.today().isoformat(),
        "---",
        "",
        "# Synthesis Suggestions",
        "",
        AUTO_HEADER,
    ]
    for c in clusters:
        lines.append("## {} ({} papers)".format(c["label"], len(c["citekeys"])))
        lines.append("")
        for ck in c["citekeys"]:
            lines.append("- [[{}]]".format(ck))
        lines.append("")
    content = "\n".join(lines)
    if path.exists() and path.read_text(encoding="utf-8") == content:
        return False
    if not cfg.dry_run:
        path.write_text(content, encoding="utf-8")
        state.trace("synthesis_suggestions", path.name,
                    "{} cluster(s)".format(len(clusters)))
    return True
